Added support for height parameter in the taxRate LCD api
terra-project/terra.js pull request #48
Opened 2020-11-29 16:37 UTC by 0xa10

I noticed that the LCD api supports a providing height for the taxRate API node. 
This feature exists in the FCD implementation of the LCD client, so I ported it over to the LCD client in terra.js
https://github.com/terra-project/fcd/blob/develop/src/lib/lcd.ts

2020-12-22 10:23 UTC, hanjukim requested changes

2020-12-22 10:23 UTC, hanjukim commented on src/client/lcd/api/TreasuryAPI.ts
> +  public async taxRate(height?: number | undefined): Promise<Dec> {
you can omit either question mark or undefined here as you prefer.

2020-12-29 21:58 UTC, 0xa10 reviewed
Self review

2020-12-29 21:58 UTC, 0xa10 commented on src/client/lcd/api/TreasuryAPI.ts
> +  public async taxRate(height?: number | undefined): Promise<Dec> {
```suggestion
  public async taxRate(height?: number): Promise<Dec> {
```

2020-12-31 07:26 UTC, merged